---
kind: pipeline
name: arm

node:
  drone_lab: true

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: rancher/dapper:v0.4.2
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    instance:
    - drone-pr.rancher.io

- name: github_binary_release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-pr.rancher.io

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
  